### ISSUE TITLE
question about coronary atery

### ISSUE THREAD

**Issue by wujy2015** [timjerman/JermanEnhancementFilter#4]
Hi,

I found this repo is really useful to me. I am working on cardiac imaging. My input image is z*512*512 contrast CT scan. Do you have any suggestion about how to filter out coronary artery vessel? Any suggestion to the parameter setting?

Best,

**Comment by timjerman** [comment]
Hi,

please take a look at example_vesselness2D.m where vessels are enhanced in 2d images. For your case you should start by adjusting the scales according to your vessel size and try various taus between 0.5 and 1, and see which one works best for you.

Regards,
Tim

**Comment by wujy2015** [comment]
Hi,

Thanks for your advice. Just curious, why not example_vesselness3D.m? but 2d?

Best,

**Comment by timjerman** [comment]
I misunderstood the 'z512512' and thought that you have a 2d image. You should definitely look at example_vesselness3D.m if you have a 3d image.

Regards,
Tim

**Comment by wujy2015** [comment]
Hi,

Thanks Tim! I am wondering if you have python or c++ version of this code?

Best,

**Comment by timjerman** [comment]
Unfortunately, I didn't have the time to implement the python and c++ implementations yet. Hopefully, I will manage to do it sometimes in the future.

**Comment by wujy2015** [comment]
Hi Tim,

If my input 3d volume spacing is [0.25; 0.468; 0.468] (in mm), and my vessel diameter is ranging from 0.5-6.0 mm, how do I calculate sigma and tau value?

Best

**Comment by timjerman** [comment]
Please read https://github.com/timjerman/JermanEnhancementFilter/issues/3 to get your answers.
