### ISSUE TITLE
Why filter each dimension with 1D kernel?

### ISSUE THREAD

**Issue by VietThan** [timjerman/JermanEnhancementFilter#6]
Hi,

I would like to first say thank you for the script for this filter, it made understanding the Frangi paper a lot easier. I only have a small question on for imgaussian() , is there any reason why you chose to filter each dimension of the image with their 1D gaussian instead of filtering the image with the 2D Gaussian?

PS: extra small question but it seems Kroon's Matlab script is wrong mathematically (at least for the 2D)?

Thank you,

Viet Than

**Comment by timjerman** [comment]
Hi,

the nice thing of gaussian filtering is its separability -> for example in 2D, a 2D convolution can be reduced to two 1D convolutions (one among rows and one among columns). By doing this we can reduce both time and memory consumption. 

Cited from [mathworks blog](https://blogs.mathworks.com/steve/2006/10/04/separable-convolution/):

> Why would you want to filter this way? Because you can do it faster. Filtering an M-by-N image with a P-by-Q filter kernel requires roughly MNPQ multiplies and adds (assuming we aren't using an implementation based on the FFT). If the kernel is separable, you can filter in two steps. The first step requires about MNP multiplies and adds. The second requires about MNQ multiplies and adds, for a total of MN(P + Q).

> For a 9-by-9 filter kernel, that's a theoretical speed-up of 4.5.

Can you elaborate on what is wrong with Kroon's Matlab script?

Regards,
Tim

**Comment by VietThan** [comment]
Hi,

Thank you for that excellent answer and source. I am floored.

For eig2image.m (Kroon):

> % Compute the eigenvectors of J, v1 and v2
> tmp = sqrt((Dxx - Dyy).^2 + 4*Dxy.^2);
> v2x = 2*Dxy; v2y = Dyy - Dxx + tmp;

I might be wrong but this doesn't look correct, or is it some math that I do not know?

Thanks again,

Viet Than

**Comment by VietThan** [comment]
OMG, I'm so sorry to Kroon, yes, he's correct. I just figured it out. Thanks again!
